### ISSUE TITLE
Request for Permission to Use Your Star Animation CSS

### ISSUE THREAD

**Issue by Beginnersguide138** [Suburbanno/Suburbanno#1]
本文 (English):
Hi Vinicius,

My name is Eisuke[Beginnersguide138](https://github.com/Beginnersguide138), and I live in Tokyo, Japan. I am 24 years old and a male devloper. I discovered your [Star animation CSS](https://codepen.io/Suburbanno/pen/OXeMvw) project on CodePen, and I am truly impressed by its beauty and creativity.

I am currently developing a chat application for my company using Chainlit as the UI framework. I would like to adapt your Star animation CSS into our project. Would you kindly grant me permission to use and modify your work?

As a token of appreciation, I would be happy for you to explore and use any of the projects I’ve shared on my CodePen profile: [https://codepen.io/SyntaxSorcererLogicLuminary](https://codepen.io/SyntaxSorcererLogicLuminary).

Thank you very much for your time and consideration. I look forward to hearing from you!

Best regards,
Eisuke

---

Texto (Português):
Olá Vinicius,

Meu nome é Eisuke ([Beginnersguide138](https://github.com/Beginnersguide138)), moro em Tóquio, Japão. Tenho 24 anos e sou um desenvolvedor. Descobri seu projeto [Star animation CSS](https://codepen.io/Suburbanno/pen/OXeMvw) no CodePen, e fiquei muito impressionado com sua beleza e criatividade.

Atualmente, estou desenvolvendo um aplicativo de chat para minha empresa usando Chainlit como framework de interface. Gostaria de adaptar seu Star animation CSS em nosso projeto. Você poderia gentilmente me conceder permissão para usar e modificar seu trabalho?

Como forma de agradecimento, ficaria muito feliz se você explorasse e utilizasse qualquer um dos projetos que compartilhei no meu perfil do CodePen: https://codepen.io/SyntaxSorcererLogicLuminary.

Muito obrigado pelo seu tempo e consideração. Espero ouvir de você em breve!

Atenciosamente,
Eisuke

**Comment by Suburbanno** [comment]
Hi, you are free to use!

**Comment by Beginnersguide138** [comment]
Thanks for your reply, and thank you so much!
